development:
  api_key: <%= ENV['SHOPIFY_APP_API_KEY'] %>
  secret: <%= ENV['SHOPIFY_APP_API_SECRET'] %>
production:
  api_key: <%= ENV['SHOPIFY_APP_API_KEY'] %>
  secret: <%= ENV['SHOPIFY_APP_API_SECRET'] %>